### PR TITLE
Bump version to v2.3.0

### PR DESCRIPTION
**Pull request by willmanduffy**
* #123

### CODE REVIEW

**Review by pliao28 — APPROVED** [review]

**Comment by pliao28** [comment]
@willmanduffy I will release version bump after deprecating VerifyFactor in favor of VerifyChallenge

**Comment by willmanduffy** [comment]
@pliao28 Sounds good. I'll hold off on this PR and you can merge in / release when it's ready?

**Comment by pliao28** [comment]
> @pliao28 Sounds good. I'll hold off on this PR and you can merge in / release when it's ready?

Yup sounds good!

**Comment by pliao28** [comment]
https://github.com/workos/workos-kotlin/pull/125 completed, merging and bumping version.

**Pull request merged**
