### PR TITLE
(WIP) Add users

### PR DESCRIPTION
**Pull request by AshGodfrey**
## Description

Adds userland 

## Documentation

Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

```
[ x] Yes -- https://github.com/workos/workos/pull/22693
```

If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is required.

### CODE REVIEW

**Review by robframpton — APPROVED** [review]

**Comment by ibrahimbutt** [comment]
@robframpton when will this be merged?

**Comment by ibrahimbutt** [comment]
@AshGodfrey is this still being worked on? If not, I am happy to take it on myself.

**Comment by ibrahimbutt** [comment]
@robframpton could you review this please so this can be merged? I have the impression that this SDK is dead, and I hope it is not the case. This has been stale for a while not and there is no usermanagement support _at all_ in this SDK.

**Review by ibrahimbutt — APPROVED** [review]

**Comment by ibrahimbutt** [comment]
@oliverzheng @tribble

Can this be approved and merged please? There is no user management support in the SDK, whereas the other SDKs have it. Are you not supporting Kotlin and Java?

I don't understand why this PR is dead, and it certainly reduces my faith in using WorkOS, considering the tooling is not being maintained or developed.

**Comment by PaulAsjes** [comment]
Hi @ibrahimbutt, apologies for the delay here. I'm going to look into getting this merged.

**Comment by southgate** [comment]
Hi @ibrahimbutt, EM on the team here responsible for this API.  Landing this PR is something we're planning to work on in the coming weeks.  Would that work for your timeline?

**Comment by ibrahimbutt** [comment]
Hi @southgate. Glad to hear this is in the pipeline! A few weeks works for our timeline. Thank you!

**Comment by ibrahimbutt** [comment]
Hi @southgate, checking in as it has been 3 weeks. Is there an ETA on this?

**Comment by southgate** [comment]
Missed this notification.  We're getting started on this shortly @ibrahimbutt. Will loop back to you with an ETA later this week.

**Comment by amadeo-workos** [comment]
@ibrahimbutt we are going to be actively working on adding user management functionality into the SDK this month. You should expect it to be ready by April 29th.

**Comment by amadeo-workos** [comment]
Closing this PR in favor of https://github.com/workos/workos-kotlin/pull/212, which contains the full support for User Management.

**Comment by ibrahimbutt** [comment]
Thank you for the updates @southgate @amadeo-workos!

**Pull request closed without merging**
